# Rename this file to languages.toml to enable multilingual support
[zh-tw]
  languageName = "繁體中文"
  languagedirection = "ltr"
  title = "Swark's blog"
  weight = 1
  [zh-tw.params]
    readingSpeed = 50

[en]
  languageName = "English"
  languagedirection = "ltr"
  title = "Swark's blog"
  weight = 2
  [en.params]
    readingSpeed = 12
