# Configure main menu and social menu
# [[main]]
# identifier = "home"
# name = "Home"
# url = "/"
# [main.params]
# icon = "home"
# newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/swark"

[social.params]
icon = "brand-github"

[[social]]
identifier = "linkin"
name = "Linkin"
url = "https://linkedin.com/in/swark-yang-790727113/"

[social.params]
icon = "linkedin"
